### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by jamesplease** [callum/morphdom-hooks#1]
!

**Comment by SilentCicero** [comment]
! +1...

**Comment by SilentCicero** [comment]
@jmeas lol @callum ... waiting :-)

**Comment by callum** [comment]
I'm on it. I've been holding off because there's a change that needs to be made to morphdom so that this works the way I had in mind. Currently the `onadd` function doesn't get called on nested elements.

``` html
<!-- tree A -->
<div>
  <div>foo</div>
</div>

<!-- tree B -->
<div>
  <div>foo</div>
  <div> <!-- onadd called -->
    <div>bar</div> <!-- onadd not called -->
    <div>baz</div> <!-- onadd not called -->
  </div>
</div>
```

I will do an initial release for now and get a PR up together for morphdom.

**Comment by callum** [comment]
Done

**Comment by jamesplease** [comment]
Sweet - thank you!
