### ISSUE TITLE
Expose options, rather than wrapping morphdom

### ISSUE THREAD

**Issue by jamesplease** [callum/morphdom-hooks#4]
It seems unexpected to me to me that `morphdom-hooks` exposes an API wraps `morphdom`, when it's just a set of morphdom options.

What's the reasoning behind that? I'd rather it just export the options tbqh.

**Comment by callum** [comment]
The API is friendlier this way. Users of morphdom can carry on using it as they currently are, passing the same options as normal.

This test, for example, makes sure that any options set on the morphdom call are properly handled https://github.com/callum/morphdom-hooks/blob/master/test.js#L9-L30

``` js
var hooks = require('morphdom-hooks')
var morphdom = hooks(require('morphdom'))

morphdom(foo, bar, {
  onBeforeElUpdated: function (toEl, fromEl) {
    console.log('works as expected')
  }
})
```

**Comment by jamesplease** [comment]
Thanks for the reply!

I see that you're forwarding along options through the fun wrapper, which is handy. I suppose I'd rather that exist in user land, rather than be the only way to access the options.

Nbd, though – gonna close this. Was just curious to hear your reasoning ✌️
